# config.yaml

general:
  mode: auto
  save_logs: true
  symbol: auto
  timeframe: M15
  timezone: Asia/Jakarta
telegram:
  enabled: true
account:
  leverage: auto
  broker_name: auto
  account_id:
  server: auto
  contract_size: auto
assets:
  weekday: XAUUSD
  weekend: BTCUSD
compound_lot:
  base_lot: 0.01
  compound_growth: 1.5
  max_lot: 2.0
  min_balance: 100.0
  reset_on_loss: true
risk_management:
  max_drawdown: 20.0
  max_margin_pct: 0.4
  risk_per_trade: 2.0
stop_loss:
  fallback: 300
  fibo_level: 0.618  # Ubah dari 0.5 menjadi 0.618
  method: fibonacci
  mode: dynamic
take_profit:
  fallback: 500
  fibo_level: 2.618  # Ubah dari 1.618 menjadi 2.618
  method: fibonacci
  mode: dynamic
  trailing_stop:
    enabled: true
    step: 50
    trigger: 200